print("Hello World!")
print("Hello Again")
print("I like typing this.")
print("This is fun.")
print("Yay! Printing.")
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
print("I am typing another line as instructed on the 'Study Drills' section.")
# print("You can't see this line if it has a '#' sign at the beginning.")
